dataset:
  annotations: /path/to/annotations/
  dataset: /path/to/annotations/
  targets:
    - call
    - dislike
    - fist
    - four
    - like
    - mute
    - ok
    - one
    - palm
    - peace
    - rock
    - stop
    - stop_inverted
    - three
    - two_up
    - two_up_inverted
    - three2
    - peace_inverted
    - no_gesture
  image_size: [320, 320]
  subset: -1
random_state: 42
device: 'cpu'
experiment_name: SSDLiteMobilenet_large
model:
  name: 'SSDLiteMobilenet_large'
  pretrained: False
  start_epoch: 0
  checkpoint: /path/to/chackpoint
optimizer:
  lr: 0.005
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  start_factor: 0.001
train_params:
  epochs: 100
  num_workers: 16
  train_batch_size: 64
  test_batch_size: 64
  prefetch_factor: 16
